### ISSUE TITLE
ERROR: ENOENT: no such file or directory, open 'node_modules/simpleheat/simpleheat.js'

### ISSUE THREAD

**Issue by gndeepan** [Leaflet/Leaflet.heat#118]
C:\Users\ELCOT\music\Leaflet.heat-gh-pages> npm run prepublish

> leaflet.heat@0.2.0 prepublish C:\Users\ELCOT\music\Leaflet.heat-gh-pages
> uglifyjs node_modules/simpleheat/simpleheat.js src/HeatLayer.js -c
-m -o dist/leaflet-heat.js

ERROR: ENOENT: no such file or directory, open 'node_modules/simpleheat/simpleheat.js'
    at Object.openSync (fs.js:458:3)
    at Object.readFileSync (fs.js:360:35)
    at read_file (C:\Users\ELCOT\AppData\Roaming\npm\node_modules\uglify-js\bin\uglifyjs:373:19)
    at C:\Users\ELCOT\AppData\Roaming\npm\node_modules\uglify-js\bin\uglifyjs:188:37
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (C:\Users\ELCOT\AppData\Roaming\npm\node_modules\uglify-js\bin\uglifyjs:187:31)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! leaflet.heat@0.2.0 prepublish: `uglifyjs node_modules/simpleheat/simpleheat.js src/HeatLayer.js -c -m -o dist/leaflet-heat.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the leaflet.heat@0.2.0 prepublish script.
npm ERR! This is probably not a problem with npm. There is likely additional logging
output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ELCOT\AppData\Roaming\npm-cache\_logs\2020-05-09T13_05_06_846Z-debug.log
PS C:\Users\ELCOT\music\Leaflet.heat-gh-pages>

**Comment by gndeepan** [comment]
plzzzzzz hlppp
