### ISSUE TITLE
Exception on certain map state changes

### ISSUE THREAD

**Issue by Nithanaroy** [Leaflet/Leaflet.heat#75]
**Message**: "Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The source width is 0."

Stack trace:

<pre>
"Error: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The source width is 0.
    at Error (native)
    at Object.draw (http://0.0.0.0:8126/js/leaflet-heat/leaflet-heat.js:6:1414)
    at e._redraw (http://0.0.0.0:8126/js/leaflet-heat/leaflet-heat.js:11:2802)
    at e._reset (http://0.0.0.0:8126/js/leaflet-heat/leaflet-heat.js:11:1864)
    at e.fireEvent (http://0.0.0.0:8126/node_modules/leaflet/dist/leaflet.js:6:5055)
    at http://0.0.0.0:8126/node_modules/leaflet/dist/leaflet.js:6:513"
</pre>

**Local Variables**
![screen shot 2016-10-25 at 11 06 55 am](https://cloud.githubusercontent.com/assets/670556/19698202/2eae6ab0-9aa3-11e6-8bba-0cec5617a3a8.png)

![screen shot 2016-10-25 at 11 05 28 am](https://cloud.githubusercontent.com/assets/670556/19698158/f78d6f2c-9aa2-11e6-8e2c-86ac559d837d.png)

**Comment by Bengreen** [comment]
I get a similar case as when I create my maps they are of 0 size. And then get resized later in the lifecycle.
Is it possible to put some guards around the getImageData call when the width or height are 0 otherwise we trigger a throw.

**Comment by kojilab** [comment]
Did you guys figure it out? I'm running into the same issue.

**Comment by mirko77** [comment]
Same issue here

**Comment by KonstantinosPetrakis** [comment]
One way to fix that is to add the initialization code in an interaction observer like this:

```js
new IntersectionObserver(() => {
    map.invalidateSize();

    var heat = L.heatLayer(
        [
            [50.5, 30.5, 0.2], // lat, lng, intensity
            [50.6, 30.4, 0.5],
        ],
        { radius: 25 }
    ).addTo(map);
}).observe(document.getElementById(mapId));
```

Or even better create the whole map inside the IntersectionObserver callback, because this might add many layers one on top of the other.

**Comment by francescam-malloci** [comment]
Same issue
